/**
 * Regenerates docs/performance.md from a live database.
 *
 * The plans in that file are pasted output, not prose — running this script is
 * how they get refreshed after a schema or index change.
 *
 *   TEST_DATABASE_URL=... npx tsx scripts/explain-report.ts
 */
import { writeFileSync } from 'node:fs';
import 'dotenv/config';
import postgres from 'postgres';

type Query = {
  id: string;
  index: string;
  description: string;
  sql: string;
  params?: unknown[];
};

const QUERIES = (userId: string): Query[] => [
  {
    id: 'F0.2-1',
    index: 'user_problems_user_status_idx',
    description: "A user's problems filtered by status",
    sql: `SELECT * FROM user_problems WHERE user_id = $1 AND status = 'solved'
          ORDER BY last_attempted_at DESC NULLS LAST LIMIT 50`,
    params: [userId],
  },
  {
    id: 'F0.2-2',
    index: 'problem_tags_type_value_idx',
    description: 'Problems filtered by difficulty + topic tag',
    sql: `SELECT p.* FROM problems p
          JOIN problem_tags t ON t.problem_id = p.id
          WHERE t.tag_type = 'topic' AND t.tag_value = 'graphs'
            AND p.difficulty = 'medium' AND p.status = 'published'
          LIMIT 50`,
  },
  {
    id: 'F0.2-3',
    index: 'daily_sessions_user_date_idx',
    description: "A user's daily_sessions for the last 90 days",
    sql: `SELECT * FROM daily_sessions WHERE user_id = $1 AND local_date >= current_date - 90
          ORDER BY local_date DESC`,
    params: [userId],
  },
  {
    id: 'F0.2-4',
    index: 'verification_methods_active_idx',
    description: 'An unconsumed verification code by (user_id, method)',
    sql: `SELECT * FROM verification_methods
          WHERE user_id = $1 AND method = 'phone' AND consumed_at IS NULL
          ORDER BY created_at DESC LIMIT 1`,
    params: [userId],
  },
];

async function main(): Promise<void> {
  const url = process.env.TEST_DATABASE_URL ?? process.env.DATABASE_URL;
  if (!url) throw new Error('TEST_DATABASE_URL or DATABASE_URL must be set.');

  const sql = postgres(url, { max: 1, onnotice: () => {} });

  try {
    const [user] = await sql`SELECT id FROM users LIMIT 1`;
    if (!user) throw new Error('No users in the database — run the index test suite first.');

    const counts = await sql`
      SELECT relname AS table, n_live_tup AS rows FROM pg_stat_user_tables ORDER BY relname
    `;

    const sections: string[] = [];
    for (const query of QUERIES(String(user.id))) {
      const rows = await sql.unsafe(
        `EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT) ${query.sql}`,
        (query.params ?? []) as never[],
      );
      const plan = rows.map((row) => row['QUERY PLAN']).join('\n');

      sections.push(
        `### ${query.id} · ${query.description}\n\n` +
          `Index this must use: \`${query.index}\`\n\n` +
          '```sql\n' +
          query.sql.replace(/^ +/gm, '  ').trim() +
          '\n```\n\n```\n' +
          plan +
          '\n```\n',
      );
    }

    const body =
      '# Query performance\n\n' +
      '> Generated by `scripts/explain-report.ts` against the integration test\n' +
      '> database. Every plan below is pasted output, not a description of one.\n\n' +
      '## Why the dataset is padded\n\n' +
      'Selectivity, not row count, decides a plan. On a 30-row catalog Postgres\n' +
      'correctly prefers a sequential scan, so an EXPLAIN there would prove\n' +
      'nothing about production. The fixture therefore loads ~50k problems with a\n' +
      '40-value topic vocabulary (3 tags each), 400 days of `daily_sessions` and\n' +
      '3k verification codes, which is the shape the indexes were designed for.\n\n' +
      '## Table sizes at capture time\n\n' +
      '| Table | Live rows |\n| --- | --- |\n' +
      counts.map((row) => `| \`${row.table}\` | ${row.rows} |`).join('\n') +
      '\n\n## Plans\n\n' +
      sections.join('\n');

    writeFileSync('docs/performance.md', body, 'utf8');
    console.log('wrote docs/performance.md');
  } finally {
    await sql.end();
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
